# <center> 06 NumPy Arrays & Indexing

In [1]:
import numpy as np

1. Create a numpy array called ‘height in inches’ from a list 10 of numbers: [66, 68, 71, 64, 61, 74, 64, 65, 70, 71].

In [6]:
height_in_inches = np.array([66, 68, 71, 64, 61, 74, 64, 65, 70, 71])
print(height_in_inches)

[66 68 71 64 61 74 64 65 70 71]


2. Create a new array called ‘height_in_feet’ and make its values equal to the values in the first array divided by 12.

In [7]:
height_in_feet = (height_in_inches/12)
print(height_in_feet)

[5.5        5.66666667 5.91666667 5.33333333 5.08333333 6.16666667
 5.33333333 5.41666667 5.83333333 5.91666667]


3. Create a 5x5 array of zeros.

In [19]:
array_of_zeros = np.zeros([5,5])
print(array_of_zeros)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


4. Create an array of random floating point numbers between 0 and 100.

In [84]:
float_array1 = np.random.random((2,2,2)) * 100
print(float_array1)
type(float_array1)

[[[93.10608531 40.22337457]
  [77.49864522 33.34719976]]

 [[21.56593757 41.22162309]
  [61.1608636  34.62032942]]]


numpy.ndarray

In [89]:
float_array2 = np.random.rand(3,2,1) * 100
print(float_array2)
type(float_array2)

[[[63.03578714]
  [22.01842093]]

 [[ 0.85453888]
  [39.89836441]]

 [[18.24527329]
  [92.93571931]]]


numpy.ndarray

5. Create an array of numbers from 0 to 75 in increments of 5.

In [34]:
num_array = np.arange(0,75,5)
print(num_array)

[ 0  5 10 15 20 25 30 35 40 45 50 55 60 65 70]
